server:
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true

management:
  security:
    enabled: false

spring:
  aop:
    proxy-target-class: true
    auto: true
  rabbitmq:
    host: paascloud-mq-rabbit
    port: 5672
    username: '{cipher}Bw7f/GkPY3UvuXF6sHBF5uo/A5AEhql/pJATMOQRkJkbnWvGxVlY2NLd+dEkU5asxQSeqxaoCoJEI2kJTrRxiyNffp+VhZm6/L+aVRu61smXn4yk/JJOd4nsWPW+T/K0jH32s3h2nNP9XyjNUoJ87KYQMRQrjPCWoSqewFLSk5oNMDZo4wKgIJ86c0bQoOYz/evPFGsVsGjhe2aBam8igQuxizU//EQXM5dzBZ7AQO7qfdPDpcCvUQCbGe44/5QEJ685l1/IOKx7eUylDcoBCbcJcfv2x0254wy9i/KgTOMGZi92Q/j7l0h6WE2X4zsB1GSh+AXYYHR6B6KwWaTM78x/vX6Jxt0u9v+uLxW7SlgERnBHLOnoDe0kD14GIXqxg='
    password: '{cipher}CK3aVg7ZQTIJKHN4FS7ga3M/rmZcfw+U+ejVUJE+R1y4GAKtZkCEKbtBd8SmmKcQbxoWB8PesqgWufUeED3ZvXbhjuGZFhA3Ae8WTk7wLT7pvaZbhue72JRlc20f/YJiNHn3+78lLh1p6C8I0+O8Y47gNw9YmSLAvEjpFEalUicAIkYmgVnu2s4FRH0vkXZLXSlx9Zk0amcfRpxbuw1eCNtHYERApAXxGrlL6JD7Xvy2gwEt8/GORaUX21TnQCD1cLB4ItOOyGuLF8tX+7rliIq9g6cfk4RTDjPoKpWQD2NusjFYPPXO0xBuqfZdyRi+wZI4Wm8wFSe93DGBf9ZnFL+9ZQ6m97kdsutTqwsBAxxp/RXSuZ0wvGB4Z4t7LMZbI='
  redis:
    host: paascloud-db-redis
    password: MaliPass123!
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: root
        login-password: MaliPass123!
  mail:
    host: smtp.163.com
    username: paascloudTest@163.com
    password: a123456
    port: 465
    protocol: smtp
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
  boot:
    admin:
      username: admin
      password: admin
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000

info:
  软件著作权: paascloud快速搭建企业级分布式微服务平台
  著作登记号: 2018SR320076
  关于我们: http://paascloud.net

paascloud:
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  aliyun:
    key:
      accessKeyId: 'your aliyun accessKeyId'
      accessKeySecret: 'your aliyun accessKeySecret'
    rocketMq:
      namesrvAddr: paascloud-mq-rocket:9876
    sms:
      signName: 快乐学习网
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: 'your sms product'
      domain: dysmsapi.aliyuncs.com
  qiniu:
    key:
      accessKey: 'your qiniu accessKey'
      secretKey: 'your qiniu secretKey'
    oss:
      privateHost: 'your qiniu oss private host'
      publicHost: 'your qiniu oss public host'
  alipay:
    callback:
      url: http://dev-api.paascloud.net/omc/pay/alipayCallback
    qrCode:
      pcPath: /data/file/qrCode/alipay
      qiniuPath: alipay/QRCode/
  zk:
    zkAddressList: paascloud-provider-zk:2181